
CREATE TABLE IF NOT EXISTS userDB (
	id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
        userName VARCHAR(50) DEFAULT NULL,
        userPassword VARCHAR(50) DEFAULT NULL
        
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;


