
CREATE TABLE IF NOT EXISTS userReviews (
	userID INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	userName VARCHAR(50) DEFAULT NULL,
        userPassword VARCHAR(50) DEFAULT NULL,
        userFirstName VARCHAR(50) DEFAULT NULL,
        userLastName VARCHAR(50) DEFAULT NULL,
	userBirthDate DATE,
	userEmail VARCHAR(100) DEFAULT NULL,
	userPhone VARCHAR(10) DEFAULT NULL,
	userADMIN BOOL DEFAULT FALSE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;


